export const dummyAssessmentData = {
    sessionName: "JEE Advanced Mock Test - 1",
    user: {
        id: "user_12345",
        name: "Aryan Sharma",
        email: "aryan.sharma@example.com",
    },
    examSub: {
        id: "exam_jee_2025",
        name: "JEE Advanced 2025",
        description: "Mock test for JEE Advanced preparation",
    },
    quizType: "FULL_LENGTH_TEST",
    type: 'topic',
    totalMarks: 300,
    score: 220,
    totalQuestions: 90,
    answeredQuestion: 85,
    questionSub: [
        {
            id: "q1",
            questionText: "What is the acceleration due to gravity on the Moon?",
            options: ["9.8 m/s²", "3.7 m/s²", "1.6 m/s²", "5.4 m/s²"],
            correctOption: 2,
            selectedOption: 2,
            subject: "Physics",
            topic: "Gravitation",
        },
        {
            id: "q2",
            questionText: "What is the IUPAC name of CH3-CH2-OH?",
            options: ["Ethanol", "Methanol", "Propanol", "Butanol"],
            correctOption: 0,
            selectedOption: 0,
            subject: "Chemistry",
            topic: "Organic Chemistry",
        },
        {
            id: "q3",
            questionText: "What is the derivative of sin(x)?",
            options: ["cos(x)", "-cos(x)", "tan(x)", "-sin(x)"],
            correctOption: 0,
            selectedOption: 0,
            subject: "Mathematics",
            topic: "Differentiation",
        },
    ],
    answeredQuestionIds: ["q1", "q2", "q3"],
    attemptNo: 1,
    totalTime: 180,
    startTime: new Date("2025-02-21T09:00:00Z"),
    endTime: new Date("2025-02-21T12:00:00Z"),
    timeTaken: 170,
    status: 'active',
    isCompleted: true,
    createdBy: {
        id: "admin_001",
        name: "Admin",
        email: "admin@example.com",
    },
    updatedBy: {
        id: "admin_002",
        name: "Moderator",
        email: "moderator@example.com",
    },
    answeredQuestions: ["q1", "q2", "q3"],
};
