name: Deploy on Development

on:
  push:
    branches:
      - dev
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Build & Deploy
        env:
            PRIVATE_KEY: ${{ secrets.DEV_SSH_PRIVATE_KEY_PEM }}
            HOSTNAME: ${{ secrets.DEV_SSH_HOST }}
            USER_NAME: ${{ secrets.DEV_SSH_USER_NAME }}

        run: |

          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -t -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} << 'EOF'
              set -e  # Exit if any command fails

              # Navigate to project directory
              cd /home/ubuntu/ai-tutor.dev.astconsulting.in/fe-ai-tutor
            
              # Stash only if there are changes
              git stash || true
              git stash clear || true
              
              # Pull latest changes
              git pull origin dev
              
              # Load Node.js environment
              export NVM_DIR=~/.nvm
              source ~/.nvm/nvm.sh
              
              # Install dependencies
              npm install
              
              # Ensure NEXT_SHARP_PATH is set correctly
              export NEXT_SHARP_PATH=node_modules/sharp
              
              # Build the project
              npm run build
              
              # Set PM2_HOME
              export PM2_HOME="/etc/pm2"

              # Restart the application with PM2
              pm2 restart ai-tutor-dev || pm2 start npm --name "ai-tutor-dev" -- run start
              
